---
# This playbook will create the target in the namespace specified in /vagrant/config.yaml

- name: Create Backup Target
  hosts: localhost
  user: vagrant
  vars_files:
    config.yaml
  roles:
  - create-target
